motor_info:
        min_pwm: 0.58 # = 1800 [ms]
        max_pwm: 0.85 #0.92 # = 1840 [ms], 0.85 = 1700 will consume 60a current
        min_thrust: 0 #[N]
        force_landing_thrust: 7 #[N]
        m_f_rate: -0.0203 
        pwm_conversion_mode: 1 # Polynominal Mode
        vel_ref_num: 4

        ref1:
                voltage: 25.2
                max_thrust: 26.3588
                polynominal4: 1.48773731 # x 10^4
                polynominal3: -5.58079254 # x10^3
                polynominal2: 5.74014278 # x10^2
                polynominal1: 5.61360996 # x10
                polynominal0: 58.88048410 # x1
        ref2:
                voltage: 24.2
                max_thrust: 24.9860 #18.07
                polynominal4: -0.49628768 # x 10^4
                polynominal3: 5.09303222 # x10^3
                polynominal2: -12.15569447 # x10^2
                polynominal1: 16.32457694 # x10
                polynominal0: 57.39893059  # x1
        ref3:
                voltage: 23.2
                max_thrust: 22.6525 #17.35
                polynominal4: -3.61914123 # x 10^4
                polynominal3: 20.17981105  # x10^3
                polynominal2: -34.70653457 # x10^2
                polynominal1: 28.25552794 # x10
                polynominal0: 55.93348594 # x1
        ref4:
                voltage: 22.2
                max_thrust: 19.7972 #15.91
                polynominal4: -11.80332335 # x 10^4
                polynominal3: 52.59262779 # x10^3
                polynominal2: -74.05979913 # x10^2
                polynominal1: 44.83750591 # x10
                polynominal0: 54.35116065 # x1

        # for simualtion
        rotor_damping_rate: 0.1 # = 0.001 / (0.01 + 0.001); 0.01: time constant; 0.001: dt
        rotor_force_noise: 0.01 # [N] but good performance in gazebo
